name: 'RLDIF_antibody_finetune'
protein_mpnn: False 
rldif: True
esmif: False
dif_large: False
temp: False
docker: False
inference: False

free_positions: False
num_samples: 4

pifold_model:
    T: 150
    t_delta: 1
    diffusion_mode: True
    num_categories: 20

    network:
        node_features: 128
        edge_features: 128
        hidden_dim: 128
        dropout: 0.1
        num_encoder_layers: 10
        k_neighbors: 30
        virtual_num: 3
        node_dist: True
        node_angle: True
        node_direct: True
        edge_dist: True
        edge_angle: True
        edge_direct: True
        updating_edges: 4
        diffusion_mode: True
        
train:
    n_epochs: 100_000
    sampling_size: 8

    data:
        batch_size_per_gpu: 16
        n_workers: 1

    lr:
        #lr: 0.00009261139159441371
        #lr: 0.0000705042
        lr: 0.001
        schedule: poly
        gamma: 2
        warmup_steps: 1000

    opt:
        optimizer: adamW

    precision: 32
    float32_matmul_precision: highest

    verbosity: 20

    checkpointing:
        n_best_to_save: 10
        save_every_n_epochs: null
        metric: "epoch_test"
        mode: "min"

    ema: 0.999
    log_path: "/home/pi-user/RLDIF_github_clean/pi-rldif/logs/"

model_mpnn:
    hidden_dim: 128
    num_layers: 3
    backbone_noise: 0.0
    dropout: 0.0
    k_neighbors: 48
    alphabet: "ACDEFGHIKLMNPQRSTVWYX"

    temperature: 0.5
    true_sample_prob: 0.0
    balanced_sampling: False
    simulated_balanced_sampling: False

data:
    dataset_name: 'cath_sub100'
    split_name: 'cath_sub100'
    #custom_pdb_input: "/home/pi-user/pdb_path/input_file.csv"
    custom_pdb_input: "/home/pi-user/ampersand_bio/input.csv"
    #custom_pdb_input: "input.csv"
    train_pdb_input: "/home/pi-user/ampersand_bio/input.csv"
    val_pdb_input: "/home/pi-user/ampersand_bio/input.csv"
    test_pdb_input: "/home/pi-user/ampersand_bio/input.csv"


