data:
  dataset_name: 'cath_sub100'
  split_name: 'cath_sub100'
  pifold: True

pifold_model:
    T: 150
    t_delta: 1
    diffusion_mode: True
    num_categories: 20

    network:
        node_features: 128
        edge_features: 128
        hidden_dim: 128
        dropout: 0.1
        num_encoder_layers: 10
        k_neighbors: 30
        virtual_num: 3
        node_dist: True
        node_angle: True
        node_direct: True
        edge_dist: True
        edge_angle: True
        edge_direct: True
        updating_edges: 4
        diffusion_mode: True

train:
    n_epochs: 100_000

    data:
        batch_size_per_gpu: 6
        update_batch_size_per_gpu: 6
        sampling_batch_size_per_gpu: 6
        n_workers: 1
        n_samples: 4

    lr:
        lr: 0.00001
        schedule: poly
        gamma: 2
        warmup_steps: 1

    opt:
        optimizer: adamW
        gradient_accumulation_steps: 1

    precision: fp32
    float32_matmul_precision: highest

    verbosity: 20

    checkpointing:
        n_best_to_save: -1

    ema: 0.999


